GET http://localhost:5000/getPreferences
Content-Type: application/json

#########
POST  http://localhost:5000/addPreferences
Content-Type: application/json

[
    {
        "_id": "5d11217d1c9d440000465111",
        "category": "Technology",
        "subCategories": ["Game Dev"]
    }
]